# Generated by Django 5.1.1 on 2024-09-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_author_post_user_remove_post_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=200, null=True, unique=True, verbose_name='URL'),
        ),
    ]
