# Generated by Django 5.1.1 on 2024-09-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='posts.wepb', upload_to='posts/'),
        ),
    ]
