# Generated by Django 5.1.1 on 2024-10-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(default=None, null=True, upload_to='uploads/video'),
        ),
    ]
