# Generated by Django 5.1.1 on 2024-12-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/video'),
        ),
    ]
