# Generated by Django 5.1.1 on 2024-12-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
    ]
