# Generated by Django 5.1.1 on 2024-09-26 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
