# Generated by Django 5.1.1 on 2025-01-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_profile_birth_date_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
